name: mpc-rl
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - pip
  - pip:
      - jax[cuda12]          # GPU JAX, switch to jax if CPU
      - tqdm
      - playground
      - mujoco
      - mujoco_mjx
      - brax
      - git+https://github.com/google/trajax # TODO: get rid of this dependency
      - lqrax # TODO: get rid of this dependency
      - mediapy
      - rsl-rl-lib
      - wandb