"""
Test MPC trajectory generation by replaying saved trajectories in environments.

This script loads a trajectory .npz file generated by gen_traj_data.py and replays it
in the corresponding environment to verify correctness. Supports both DM Control environments
(cartpole, walker) and custom Gymnasium environments (shadow_hand_gym).

Usage Examples:

    # Test a random cartpole trajectory
    python tests/gen_traj_data_test.py --data-dir=data/cartpole_0_010dt --domain=cartpole --task=swingup

    # Test a random walker trajectory with camera tracking
    python tests/gen_traj_data_test.py --data-dir=data/walker_0_0025dt --domain=walker --task=walk

    # Test a shadow hand trajectory
    python tests/gen_traj_data_test.py --data-dir=data/shadow_hand_0_002dt --domain=shadow_hand

    # Test a specific trajectory file
    python tests/gen_traj_data_test.py --data-dir=data/cartpole_0_010dt --domain=cartpole --task=swingup \
        --filename="qpos_[0.00,3.14]_qvel_[0.00,0.00]_rh_10000.npz"

    # Limit visualization to 1000 steps
    python tests/gen_traj_data_test.py --data-dir=data/walker_0_0025dt --domain=walker --task=walk --max-steps=1000
"""

import numpy as np
from dm_control import suite
from shimmy import DmControlCompatibilityV0
from gymnasium.wrappers import FlattenObservation
import matplotlib.pyplot as plt
from matplotlib import animation
import sys
from pathlib import Path
import random
import argparse
import gymnasium as gym

# Add parent directory to path to import from mpc_rl
sys.path.insert(0, str(Path(__file__).parent.parent))

from mpc_rl.planner.mpc_planner import MPCPlanner

# Import shadow_hand_gym to register the environments
try:
    import shadow_hand_gym
except ImportError:
    print("Warning: shadow_hand_gym not found. Shadow hand environments will not be available.")
    pass


def physical_to_normalized_action(physical_ctrl, ctrlrange):
    """
    [DEPRECATED] This function is no longer needed since gymnasium shadow_hand environment
    was updated to accept physical controls directly (matching MPC behavior).
    
    Kept for backward compatibility with other code that might still use it.
    
    Convert physical control values to normalized actions in [-1, 1] range.
    
    This is necessary because:
    - MPC stores physical control values (actual actuator positions/torques within ctrlrange)
    - Gymnasium environments expect normalized actions in [-1, 1]
    - The environment's _set_action() method transforms normalized actions to physical controls
    
    The transformation applied by _set_action() is:
        actuation_center = (ctrlrange[:, 1] + ctrlrange[:, 0]) / 2.0
        actuation_range = (ctrlrange[:, 1] - ctrlrange[:, 0]) / 2.0
        physical = actuation_center + normalized_action * actuation_range
    
    So to reverse it:
        normalized_action = (physical - actuation_center) / actuation_range
    
    Args:
        physical_ctrl: Physical control values from MPC (shape: [n_actuators])
        ctrlrange: Control ranges from model.actuator_ctrlrange (shape: [n_actuators, 2])
    
    Returns:
        normalized_action: Normalized actions in [-1, 1] range (shape: [n_actuators])
    """
    actuation_center = (ctrlrange[:, 1] + ctrlrange[:, 0]) / 2.0
    actuation_range = (ctrlrange[:, 1] - ctrlrange[:, 0]) / 2.0
    normalized_action = (physical_ctrl - actuation_center) / actuation_range
    return normalized_action


def select_trajectory(data_dir, random_select=True, filename=None):
    """
    Select a trajectory file from the data directory.
    
    Args:
        data_dir: Path to data directory
        random_select: If True, randomly select a file. If False, use filename argument.
        filename: Specific filename to load (used when random_select=False)
    
    Returns:
        Path to selected trajectory file
    """
    data_dir = Path(data_dir)
    
    if not data_dir.exists():
        raise FileNotFoundError(f"Data directory not found: {data_dir}")
    
    # Get all trajectory files
    traj_files = list(data_dir.glob("*.npz"))
    
    if len(traj_files) == 0:
        raise FileNotFoundError(f"No trajectory files found in {data_dir}")
    
    if random_select:
        selected_file = random.choice(traj_files)
        print(f"Randomly selected: {selected_file.name}")
    else:
        if filename is None:
            raise ValueError("filename must be provided when random_select=False")
        selected_file = data_dir / filename
        if not selected_file.exists():
            raise FileNotFoundError(f"File not found: {selected_file}")
        print(f"Selected: {selected_file.name}")
    
    return selected_file


def get_env_config(domain_name, task_name):
    """
    Get environment-specific configuration parameters.
    
    Args:
        domain_name: Domain name (e.g., 'cartpole', 'walker', 'shadow_hand')
        task_name: Task name (e.g., 'swingup', 'walk', None for shadow_hand)
    
    Returns:
        dict: Configuration including control_timestep, camera_id, obs_mapping, env_type
    """
    configs = {
        'cartpole': {
            'control_timestep': 0.01,  # 10ms per step
            'camera_id': None,  # Use default camera
            'obs_dims': {
                'qpos': 2,  # cart position, pole angle
                'qvel': 2   # cart velocity, pole angular velocity
            },
            'env_type': 'dm_control'
        },
        'walker': {
            'control_timestep': 0.025,  # 25ms per step
            'camera_id': 'side',  # Use side tracking camera
            'obs_dims': {
                'qpos': 9,  # rootz, rootx, rooty, right_hip, right_knee, right_ankle, left_hip, left_knee, left_ankle
                'qvel': 9   # corresponding velocities
            },
            'env_type': 'dm_control'
        },
        'shadow_hand': {
            'control_timestep': 0.002,  # 2ms per step
            'camera_id': 0,  # Default camera
            'obs_dims': {
                'qpos': 35,  # 4 (cube quat) + 3 (cube pos) + 2 (cube joints) + 24 (hand joints) + 2 (extra)
                'qvel': 33   # corresponding velocities (quaternion has one less vel dimension)
            },
            'env_type': 'gymnasium',
            'env_id': 'ShadowHandManipulateBlockRotateXYZDense-v1'
        }
    }
    
    if domain_name not in configs:
        raise ValueError(f"Unsupported domain: {domain_name}. Supported: {list(configs.keys())}")
    
    return configs[domain_name]


def test_trajectory_in_environment(data_dir, domain_name='cartpole', task_name='swingup', 
                                   random_select=True, filename=None, max_steps=500):
    """
    Test a saved MPC trajectory by running its downsampled controls through an environment.
    This verifies that the MPC-planned trajectory works in the RL environment.
    
    Args:
        data_dir: Path to directory containing trajectory .npz files
        domain_name: Domain name (e.g., 'cartpole', 'walker', 'shadow_hand')
        task_name: Task name (e.g., 'swingup', 'walk', None for shadow_hand)
        random_select: If True, randomly select a trajectory file
        filename: Specific filename to load (used when random_select=False)
        max_steps: Maximum number of steps to visualize
    """
    # Get environment configuration
    env_config = get_env_config(domain_name, task_name)
    
    # Select a trajectory file from data directory
    traj_file = select_trajectory(data_dir, random_select=random_select, filename=filename)
    
    # Load the trajectory data
    print(f"\nLoading trajectory from: {traj_file}")
    data = np.load(traj_file)
    qpos = data["qpos"]
    qvel = data["qvel"]
    ctrl = data["ctrl"]
    time = data["time"]
    
    # For shadow_hand, we need to extract the initial state from the trajectory
    # For dm_control, we have init_qpos and init_qvel stored directly
    if domain_name == 'shadow_hand':
        # Initial state is the first column of qpos/qvel
        init_qpos = qpos[:, 0]
        init_qvel = qvel[:, 0]
    else:
        init_qpos = data["init_qpos"]
        init_qvel = data["init_qvel"]
    
    print(f"Initial state: qpos shape={init_qpos.shape}, qvel shape={init_qvel.shape}")
    print(f"Trajectory length: {qpos.shape[1]} steps")
    print(f"Control shape: {ctrl.shape}")
    
    # Infer downsample factor from MPC timestep and environment control timestep
    # MPC timestep is the spacing between consecutive time points
    mpc_timestep = time[1] - time[0]
    control_timestep = env_config['control_timestep']
    downsample_factor = int(round(control_timestep / mpc_timestep))
    
    print(f"MPC timestep: {mpc_timestep:.4f}s")
    print(f"Environment control timestep: {control_timestep:.4f}s")
    print(f"Downsample factor: {downsample_factor}")
    
    # Downsample the control trajectory
    ctrl_downsampled = ctrl[:, ::downsample_factor]
    time_downsampled = time[:-1:downsample_factor]
    
    print(f"Downsampled control length: {ctrl_downsampled.shape[1]} steps")
    
    # Plot original vs downsampled control (show first 4 actuators for visualization)
    num_actuators_to_plot = min(4, ctrl.shape[0])
    fig1, axes = plt.subplots(num_actuators_to_plot, 2, figsize=(12, 3 * num_actuators_to_plot))
    if num_actuators_to_plot == 1:
        axes = axes.reshape(1, -1)
    
    for actuator_idx in range(num_actuators_to_plot):
        # Original control
        axes[actuator_idx, 0].plot(time[:-1], ctrl[actuator_idx, :], color="blue")
        axes[actuator_idx, 0].set_xlabel("Time (s)")
        axes[actuator_idx, 0].set_ylabel(f"Control (actuator {actuator_idx})")
        axes[actuator_idx, 0].set_title(f"Original Control Signal (MPC) - Actuator {actuator_idx}")
        axes[actuator_idx, 0].grid(True)
        
        # Downsampled control
        axes[actuator_idx, 1].plot(time_downsampled, ctrl_downsampled[actuator_idx, :], 
                                   color="red", marker='o', linestyle='-', markersize=3)
        axes[actuator_idx, 1].set_xlabel("Time (s)")
        axes[actuator_idx, 1].set_ylabel(f"Control (actuator {actuator_idx})")
        axes[actuator_idx, 1].set_title(f"Downsampled Control (Factor: {downsample_factor}) - Actuator {actuator_idx}")
        axes[actuator_idx, 1].grid(True)
    
    plt.tight_layout()
    plt.show()
    
    # Create environment based on type
    print(f"\nCreating {domain_name} {task_name if task_name else ''} environment...")
    
    if env_config['env_type'] == 'dm_control':
        # DM Control environment
        dm_env = suite.load(domain_name=domain_name, task_name=task_name)
        env = DmControlCompatibilityV0(dm_env, render_mode="rgb_array")
        env = FlattenObservation(env)
    else:
        # Gymnasium environment (shadow_hand)
        env = gym.make(env_config['env_id'], render_mode="rgb_array")
    
    # Reset environment first
    obs, info = env.reset()
    
    # Set the environment to the MPC initial state
    if env_config['env_type'] == 'dm_control':
        # Access the underlying dm_control physics and set qpos/qvel directly
        env.unwrapped._env.physics.data.qpos[:] = init_qpos
        env.unwrapped._env.physics.data.qvel[:] = init_qvel
        # Forward the physics to ensure consistent state
        env.unwrapped._env.physics.forward()
    else:
        # For gymnasium shadow_hand, access the MuJoCo data directly
        env.unwrapped.data.qpos[:] = init_qpos
        env.unwrapped.data.qvel[:] = init_qvel
        
        # Also update the goal in the environment to match the trajectory
        # The goal is stored in qpos[0:4] (ball joint - quaternion only)
        # and needs to be set in both data.qpos and env.goal
        goal_quat = init_qpos[0:4]  # Extract goal orientation from trajectory
        
        # Update the environment's goal to match the trajectory
        # The goal in shadow hand is 7D: [x, y, z, qw, qx, qy, qz]
        # We need to get the goal position from the goal body and combine with saved quat
        import mujoco
        goal_body_id = mujoco.mj_name2id(env.unwrapped.model, mujoco.mjtObj.mjOBJ_BODY, "goal")
        goal_pos = env.unwrapped.data.xpos[goal_body_id].copy()  # Get current goal position
        
        # Set the environment's goal (used for reward calculation)
        env.unwrapped.goal = np.concatenate([goal_pos, goal_quat])
        
        # Forward the physics to ensure consistent state
        mujoco.mj_forward(env.unwrapped.model, env.unwrapped.data)
    
    print(f"Environment initialized to initial state from trajectory")
    if domain_name == 'shadow_hand':
        print(f"  Goal orientation set to: {goal_quat}")
    
    # Collect frames by applying downsampled controls
    print("Applying downsampled controls to environment...")
    frames = []
    states_from_env = []
    
    # Get initial frame
    if env_config['env_type'] == 'dm_control':
        camera_id = env_config['camera_id']
        if camera_id:
            frame = env.unwrapped._env.physics.render(camera_id=camera_id, height=480, width=640)
        else:
            frame = env.render()
    else:
        # For gymnasium environment
        frame = env.render()
    
    frames.append(frame)
    
    # Apply each control action
    num_steps = min(ctrl_downsampled.shape[1], max_steps)
    for t in range(num_steps):
        # MPC controls are already in physical space, which is what the environment expects
        action = ctrl_downsampled[:, t]
        
        # Step environment normally
        obs, reward, terminated, truncated, info = env.step(action)
        
        # Render and save frame
        if env_config['env_type'] == 'dm_control':
            if camera_id:
                frame = env.unwrapped._env.physics.render(camera_id=camera_id, height=480, width=640)
            else:
                frame = env.render()
        else:
            frame = env.render()
        
        frames.append(frame)
        states_from_env.append(obs)
        
        if terminated or truncated:
            print(f"Episode ended at step {t+1}/{num_steps}")
            print(f"  Terminated: {terminated}, Truncated: {truncated}")
            if 'is_success' in info:
                print(f"  Success: {info['is_success']}")
            print(f"  Final reward: {reward}")
            break
    
    env.close()
    print(f"Collected {len(frames)} frames")
    
    # Create animation
    print("Creating animation...")
    fig_anim = plt.figure(figsize=(10, 8))
    img = plt.imshow(frames[0])
    plt.axis('off')
    plt.title(f"{domain_name} {task_name if task_name else ''}: {traj_file.name}")
    
    def animate(i):
        img.set_data(frames[i])
        return [img]
    
    # Calculate FPS based on environment timestep
    FPS = 1.0 / control_timestep
    
    anim = animation.FuncAnimation(fig_anim, animate, frames=len(frames), 
                                   interval=1000/FPS, blit=True, repeat=True)
    print(f"Animation created with {len(frames)} frames at {FPS:.1f} FPS")
    
    plt.show()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Test MPC trajectories by replaying them in environments"
    )
    parser.add_argument(
        "--data-dir",
        type=str,
        required=True,
        help="Path to directory containing trajectory .npz files (e.g., 'data/walker_0_0025dt/')"
    )
    parser.add_argument(
        "--domain",
        type=str,
        required=True,
        choices=['cartpole', 'walker', 'shadow_hand'],
        help="Domain name (cartpole, walker, shadow_hand)"
    )
    parser.add_argument(
        "--task",
        type=str,
        default=None,
        help="Task name (e.g., 'swingup' for cartpole, 'walk' for walker). Not needed for shadow_hand."
    )
    parser.add_argument(
        "--filename",
        type=str,
        default=None,
        help="Specific trajectory filename to load (if not specified, randomly selects one)"
    )
    parser.add_argument(
        "--max-steps",
        type=int,
        default=500,
        help="Maximum number of steps to visualize (default: 500)"
    )
    
    args = parser.parse_args()
    
    # Validate task argument
    if args.domain in ['cartpole', 'walker'] and args.task is None:
        parser.error(f"--task is required for domain '{args.domain}'")
    
    # Test the trajectory in the environment
    test_trajectory_in_environment(
        data_dir=args.data_dir,
        domain_name=args.domain,
        task_name=args.task,
        random_select=(args.filename is None),
        filename=args.filename,
        max_steps=args.max_steps
    )