"""
Test MPX quadruped trajectory generation by replaying saved trajectories in the RL environment.

This script loads a trajectory .npz file generated by gen_traj_data_mpx.py and replays it
in QuadrupedVelocityTrackingEnv to verify correctness. The RL environment uses its default
PD gains (kp=[20,20,40,...], kd=[1,1,2,...]) and action_scale -- the same configuration
used during training.

The replay works via per-substep inverse PD: at every simulation substep, the recorded
total torque and the current env state are used to compute a joint position target that
makes the RL PD controller reproduce the exact recorded torque. Because the target is
recomputed at each substep rather than held fixed for the entire control step, the replay
is exact regardless of the PD gain mismatch between MPX and the RL env.

The equivalent RL action (one per control step) is also computed from the first substep's
inverse PD for diagnostic purposes. Actions that exceed [-1, 1] are reported as clipping.

Usage Examples:

    # Test a random trajectory from the default directory
    python tests/gen_traj_data_test_quad.py --data-dir=data/quadruped

    # Test a specific trajectory file
    python tests/gen_traj_data_test_quad.py --data-dir=data/quadruped \
        --filename="quadruped_seed_000000_ep_1000.npz"

    # Limit visualization to 200 control steps
    python tests/gen_traj_data_test_quad.py --data-dir=data/quadruped --max-steps=200

    # Use torque replay mode instead of joint position replay
    python tests/gen_traj_data_test_quad.py --data-dir=data/quadruped --replay-mode=torque
"""

import time
import numpy as np
import argparse
from pathlib import Path
import sys

import mujoco
import matplotlib.pyplot as plt
from matplotlib import animation

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from mpc_rl.envs.velocity_tracking_env import QuadrupedVelocityTrackingEnv
from mpc_rl.envs.domain_randomization import DomainRandomizationConfig


def select_trajectory(data_dir, random_select=True, filename=None):
    """Select a trajectory file from the data directory."""
    data_dir = Path(data_dir)

    if not data_dir.exists():
        raise FileNotFoundError(f"Data directory not found: {data_dir}")

    traj_files = sorted(data_dir.glob("*.npz"))

    if len(traj_files) == 0:
        raise FileNotFoundError(f"No .npz files found in {data_dir}")

    if random_select:
        selected = traj_files[np.random.randint(len(traj_files))]
        print(f"Randomly selected: {selected.name}")
    else:
        if filename is None:
            raise ValueError("filename must be provided when random_select=False")
        selected = data_dir / filename
        if not selected.exists():
            raise FileNotFoundError(f"File not found: {selected}")

    return selected


def load_trajectory(traj_file):
    """Load and parse an MPX quadruped trajectory file.

    Returns:
        dict with parsed trajectory data.
    """
    data = np.load(traj_file, allow_pickle=True)

    result = {
        "qpos": data["qpos"],                      # (nq, T+1)
        "qvel": data["qvel"],                      # (nv, T+1)
        "tau_applied": data["tau_applied"],         # (n_joints, T)
        "tau_mpx": data["tau_mpx"],                 # (n_joints, T)
        "q_des": data["q_des"],                     # (n_joints, T)
        "time": data["time"],                       # (T+1,)
        "commands": data["commands"],               # (3, T)
        "seed": int(data["seed"]),
        "default_joint_pos": data["default_joint_pos"],
        "action_scale": float(data["action_scale"]),
        "sim_dt": float(data["sim_dt"]),
        "control_dt": float(data["control_dt"]),
        "episode_length": int(data["episode_length"]),
    }
    return result


def replay_joint_position_mode(env, traj, max_steps, render_mode=None):
    """Replay trajectory using per-substep inverse PD torque matching.

    At each simulation substep, computes the joint position target that makes
    the RL env's PD controller produce the exact recorded torque:

        q_target = q + (tau_recorded + kd * dq) / kp

    Substituting into the PD law verifies this is exact (for any gains):

        tau = kp * (q_target - q) - kd * dq
            = kp * ((tau_recorded + kd * dq) / kp) - kd * dq
            = tau_recorded + kd * dq - kd * dq
            = tau_recorded

    Because the target is recomputed at every substep (not held fixed for the
    control step), the replay exactly reproduces the recorded torques and
    state evolution regardless of the env's PD gains.

    The equivalent RL action is computed at each control step from the first
    substep's inverse PD, for logging and MPC injection diagnostic purposes.

    Args:
        env: QuadrupedVelocityTrackingEnv instance (already initialized to start state).
        traj: Parsed trajectory data dict (recorded at sim frequency).
        max_steps: Maximum control steps to replay.
        render_mode: Render mode string. When "human", sleeps between frames
            to maintain real-time playback speed.

    Returns:
        Tuple of (frames, env_qpos_history, env_qvel_history, actions_applied).
    """
    sim_dt = traj["sim_dt"]
    control_dt = traj["control_dt"]
    decimation = int(round(control_dt / sim_dt))  # 4
    default_joint_pos = traj["default_joint_pos"]
    tau_applied = traj["tau_applied"]
    commands_recorded = traj["commands"]
    episode_length = traj["episode_length"]

    action_scale = env.action_scale
    kp = env.kp
    kd = env.kd

    num_steps = min(episode_length, max_steps)

    frames = []
    env_qpos_history = []
    env_qvel_history = []
    actions_applied = []
    rewards = []
    clip_count = 0
    max_raw_action = 0.0

    # Get initial frame
    frame = env.render()
    if frame is not None:
        frames.append(frame)

    print(f"Replaying {num_steps} control steps with per-substep inverse PD...")
    print(f"  Env gains: kp={kp[:3]}..., kd={kd[:3]}..., action_scale={action_scale}")

    for ctrl_step in range(num_steps):
        sim_idx_start = ctrl_step * decimation

        # Set velocity commands to match what MPX was tracking
        cmd = commands_recorded[:, sim_idx_start]
        env.set_commands(vx=cmd[0], vy=cmd[1], wz=cmd[2])

        # Compute equivalent RL action from the first substep's inverse PD.
        # This is what an RL policy would need to output (diagnostic only).
        q_first = env.mjData.qpos[7:19].copy()
        dq_first = env.mjData.qvel[6:18].copy()
        tau_first = tau_applied[:, sim_idx_start]
        q_target_first = q_first + (tau_first + kd * dq_first) / kp
        action = (q_target_first - default_joint_pos) / action_scale
        raw_action = action.copy()
        action_clipped = np.clip(action, -1.0, 1.0)

        raw_max = np.max(np.abs(raw_action))
        if raw_max > max_raw_action:
            max_raw_action = raw_max
        if np.any(np.abs(raw_action) > 1.0):
            clip_count += 1

        # Update env's action tracking (mirrors env.step() bookkeeping)
        env._prev_last_action = env._last_action.copy()
        env._last_action = action_clipped.copy()

        # -- Per-substep torque application --
        # Instead of env.step() (which holds q_target fixed for all substeps),
        # apply the recorded torque at each substep via the inverse PD identity.
        for sub in range(decimation):
            sim_idx = sim_idx_start + sub
            if sim_idx >= tau_applied.shape[1]:
                break

            torques = tau_applied[:, sim_idx].copy()
            torques = np.clip(
                torques,
                env.torque_limits[:, 0],
                env.torque_limits[:, 1],
            )
            env._applied_torques = torques
            env.mjData.ctrl[:] = torques
            mujoco.mj_step(env.mjModel, env.mjData)

        # -- Replicate env.step() post-substep bookkeeping --
        env._step_count += 1
        env._steps_since_command_resample += 1
        env._maybe_push_robot()
        env._update_feet_air_time()

        joint_vel_current = env.mjData.qvel[6:].copy()
        env._joint_acc = (joint_vel_current - env._last_joint_vel) / env.control_dt
        env._last_joint_vel = joint_vel_current

        obs = env._get_obs()
        terminated = env._check_termination()
        reward = env._compute_reward(action_clipped, terminated)
        env._swing_peak *= ~env._current_contacts

        # Record
        env_qpos_history.append(env.mjData.qpos.copy())
        env_qvel_history.append(env.mjData.qvel.copy())
        actions_applied.append(action_clipped.copy())
        rewards.append(reward)

        frame = env.render()
        if frame is not None:
            frames.append(frame)
        if render_mode == "human":
            time.sleep(control_dt / 2)

        if terminated:
            print(f"  Episode terminated at step {ctrl_step+1}/{num_steps}")
            break

        if (ctrl_step + 1) % 200 == 0:
            print(f"  Step {ctrl_step+1}/{num_steps}, reward={reward:.4f}")

    env_qpos_history = np.array(env_qpos_history)  # (steps, nq)
    env_qvel_history = np.array(env_qvel_history)  # (steps, nv)
    actions_applied = np.array(actions_applied)     # (steps, n_joints)

    print(f"  Total reward: {sum(rewards):.2f}, mean: {np.mean(rewards):.4f}")
    if clip_count > 0:
        print(f"  Action clipping: {clip_count}/{len(rewards)} steps had |action| > 1.0")
        print(f"  Max |raw action|: {max_raw_action:.3f}")

    return frames, env_qpos_history, env_qvel_history, actions_applied


def replay_torque_mode(env, traj, max_steps, render_mode=None):
    """Replay trajectory by directly applying recorded torques.

    Bypasses the RL env's PD controller by directly setting torques from
    the MPX trajectory. This gives the closest match to the original trajectory.

    Args:
        env: QuadrupedVelocityTrackingEnv instance (already initialized to start state).
        traj: Parsed trajectory data dict.
        max_steps: Maximum control steps to replay.
        render_mode: Render mode string. When "human", sleeps between frames
            to maintain real-time playback speed.

    Returns:
        Tuple of (frames, env_qpos_history, env_qvel_history).
    """
    sim_dt = traj["sim_dt"]
    control_dt = traj["control_dt"]
    decimation = int(round(control_dt / sim_dt))  # 4
    tau_applied = traj["tau_applied"]
    commands_recorded = traj["commands"]
    episode_length = traj["episode_length"]
    total_sim_steps = tau_applied.shape[1]

    num_ctrl_steps = min(episode_length, max_steps)
    num_sim_steps = num_ctrl_steps * decimation

    frames = []
    env_qpos_history = []
    env_qvel_history = []

    frame = env.render()
    if frame is not None:
        frames.append(frame)

    print(f"Replaying {num_ctrl_steps} control steps in torque mode...")

    for sim_step in range(min(num_sim_steps, total_sim_steps)):
        # Directly apply the recorded torques to MuJoCo
        torques = tau_applied[:, sim_step]
        env.mjData.ctrl[:] = torques
        mujoco.mj_step(env.mjModel, env.mjData)

        # Record at control frequency
        if (sim_step + 1) % decimation == 0:
            env_qpos_history.append(env.mjData.qpos.copy())
            env_qvel_history.append(env.mjData.qvel.copy())

            frame = env.render()
            if frame is not None:
                frames.append(frame)
            if render_mode == "human":
                time.sleep(control_dt)

            ctrl_step = (sim_step + 1) // decimation
            if ctrl_step % 200 == 0:
                print(f"  Step {ctrl_step}/{num_ctrl_steps}")

    env_qpos_history = np.array(env_qpos_history)
    env_qvel_history = np.array(env_qvel_history)

    return frames, env_qpos_history, env_qvel_history


def plot_trajectory_comparison(traj, env_qpos_history, replay_mode, max_steps):
    """Plot comparison between recorded MPX trajectory and RL env replay.

    Shows joint positions, base position/orientation, and base velocities.
    """
    sim_dt = traj["sim_dt"]
    control_dt = traj["control_dt"]
    decimation = int(round(control_dt / sim_dt))
    qpos_recorded = traj["qpos"]
    qvel_recorded = traj["qvel"]
    time_recorded = traj["time"]
    commands = traj["commands"]
    episode_length = traj["episode_length"]

    num_steps = min(len(env_qpos_history), min(episode_length, max_steps))

    # Build time axes
    t_ctrl = np.arange(num_steps) * control_dt
    # Recorded at control frequency (downsample from sim)
    rec_indices = np.arange(num_steps) * decimation
    valid_indices = rec_indices[rec_indices < qpos_recorded.shape[1]]
    num_valid = len(valid_indices)
    t_ctrl_valid = t_ctrl[:num_valid]

    # -- 1) Base position (x, y, z) --
    fig1, axes1 = plt.subplots(3, 1, figsize=(12, 8), sharex=True)
    base_labels = ["x", "y", "z"]
    for i in range(3):
        rec = qpos_recorded[i, valid_indices]
        env = env_qpos_history[:num_valid, i]
        axes1[i].plot(t_ctrl_valid, rec, 'b-', label='MPX recorded', alpha=0.8)
        axes1[i].plot(t_ctrl_valid, env, 'r--', label=f'RL replay ({replay_mode})', alpha=0.8)
        axes1[i].set_ylabel(f"Base {base_labels[i]} (m)")
        axes1[i].legend()
        axes1[i].grid(True)
    axes1[0].set_title("Base Position Comparison")
    axes1[-1].set_xlabel("Time (s)")
    plt.tight_layout()
    plt.show()

    # -- 2) Joint positions (first 4 joints: one per leg) --
    joint_names = [
        "FL_hip", "FL_thigh", "FL_calf",
        "FR_hip", "FR_thigh", "FR_calf",
        "RL_hip", "RL_thigh", "RL_calf",
        "RR_hip", "RR_thigh", "RR_calf",
    ]
    fig2, axes2 = plt.subplots(4, 1, figsize=(12, 10), sharex=True)
    for leg_idx in range(4):
        joint_idx = leg_idx * 3 + 1  # thigh joint of each leg
        qpos_idx = 7 + joint_idx
        rec = qpos_recorded[qpos_idx, valid_indices]
        env = env_qpos_history[:num_valid, qpos_idx]
        axes2[leg_idx].plot(t_ctrl_valid, rec, 'b-', label='MPX recorded', alpha=0.8)
        axes2[leg_idx].plot(t_ctrl_valid, env, 'r--', label=f'RL replay ({replay_mode})', alpha=0.8)
        axes2[leg_idx].set_ylabel(f"{joint_names[joint_idx]} (rad)")
        axes2[leg_idx].legend()
        axes2[leg_idx].grid(True)
    axes2[0].set_title("Thigh Joint Position Comparison (one per leg)")
    axes2[-1].set_xlabel("Time (s)")
    plt.tight_layout()
    plt.show()

    # -- 3) Velocity commands --
    fig3, axes3 = plt.subplots(3, 1, figsize=(12, 6), sharex=True)
    cmd_labels = ["vx (m/s)", "vy (m/s)", "wz (rad/s)"]
    for i in range(3):
        # Commands at sim frequency, downsample to control frequency
        cmd_vals = commands[i, valid_indices]
        axes3[i].plot(t_ctrl_valid, cmd_vals, 'g-', linewidth=2)
        axes3[i].set_ylabel(cmd_labels[i])
        axes3[i].grid(True)
    axes3[0].set_title("Velocity Commands During Trajectory")
    axes3[-1].set_xlabel("Time (s)")
    plt.tight_layout()
    plt.show()

    # -- 4) Joint position error over time --
    fig4, ax4 = plt.subplots(figsize=(12, 4))
    errors = []
    for step in range(num_valid):
        rec_joints = qpos_recorded[7:19, valid_indices[step]]
        env_joints = env_qpos_history[step, 7:19]
        errors.append(np.linalg.norm(rec_joints - env_joints))
    ax4.plot(t_ctrl_valid, errors, 'k-')
    ax4.set_xlabel("Time (s)")
    ax4.set_ylabel("Joint position error (L2 norm, rad)")
    ax4.set_title("Joint Position Tracking Error (MPX vs RL replay)")
    ax4.grid(True)
    plt.tight_layout()
    plt.show()


def _match_generation_friction(env, tangential=0.7, torsional=0.005, rolling=0.0):
    """Set floor and foot geom friction to match the generation environment.

    QuadrupedEnv._set_ground_friction() applies the same friction values to
    floor-like geoms and foot geoms. Replicate that here so the RL env's
    contact dynamics match exactly.
    """
    friction = np.array([tangential, torsional, rolling])
    floor_names = {"ground", "floor", "hfield", "terrain"}

    foot_geom_ids = set(env._foot_geom_ids.values())

    for geom_id in range(env.mjModel.ngeom):
        geom_name = mujoco.mj_id2name(
            env.mjModel, mujoco.mjtObj.mjOBJ_GEOM, geom_id
        )
        if (geom_name and geom_name.lower() in floor_names) or geom_id in foot_geom_ids:
            env.mjModel.geom_friction[geom_id, :] = friction


def test_trajectory(data_dir, random_select=True, filename=None,
                    max_steps=500, replay_mode="joint_position",
                    render_mode="rgb_array"):
    """Test a saved MPX trajectory by replaying it in the RL environment.

    Args:
        data_dir: Path to directory containing trajectory .npz files.
        random_select: If True, randomly select a trajectory file.
        filename: Specific filename to load.
        max_steps: Maximum control steps to replay.
        replay_mode: "joint_position" or "torque".
        render_mode: Render mode for the environment.
    """
    # Select and load trajectory
    traj_file = select_trajectory(data_dir, random_select=random_select, filename=filename)
    print(f"\nLoading trajectory from: {traj_file}")
    traj = load_trajectory(traj_file)

    print(f"  Seed: {traj['seed']}")
    print(f"  Episode length: {traj['episode_length']} control steps")
    print(f"  qpos shape: {traj['qpos'].shape}")
    print(f"  qvel shape: {traj['qvel'].shape}")
    print(f"  sim_dt: {traj['sim_dt']}s, control_dt: {traj['control_dt']}s")
    print(f"  default_joint_pos: {traj['default_joint_pos']}")
    print(f"  action_scale: {traj['action_scale']}")

    # Create RL environment with default PD gains and action_scale.
    # Domain randomization is disabled so the MuJoCo model matches the
    # generation environment exactly. The per-substep inverse PD replay
    # reproduces exact torques regardless of gain mismatch.
    print(f"\nCreating QuadrupedVelocityTrackingEnv (DR disabled, default gains)...")
    env = QuadrupedVelocityTrackingEnv(
        robot="go2",
        scene="flat",
        render_mode=render_mode,
        domain_rand_cfg=DomainRandomizationConfig(enable=False, push_robots=False),
    )

    # Match ground friction to the generation environment.
    # gen_traj_data_mpx.py creates QuadrupedEnv with ground_friction_coeff=0.7,
    # which sets friction to [0.7, 0.005, 0.0] on the floor and all foot geoms.
    _match_generation_friction(env, tangential=0.7, torsional=0.005, rolling=0.0)

    # Disable early termination during replay so we can observe the full
    # trajectory even if small errors accumulate. The replay is diagnostic,
    # not training, so termination thresholds should be permissive.
    env.max_pitch = np.pi
    env.max_roll = np.pi
    env.min_base_height = -1.0

    # Reset the environment
    obs, info = env.reset(seed=42)

    # Set the initial state from the recorded trajectory
    init_qpos = traj["qpos"][:, 0]
    init_qvel = traj["qvel"][:, 0]

    env.mjData.qpos[:] = init_qpos
    env.mjData.qvel[:] = init_qvel
    env.mjData.ctrl[:] = 0.0
    env.mjData.qacc_warmstart[:] = 0.0
    mujoco.mj_forward(env.mjModel, env.mjData)

    # Reset internal tracking state after setting initial state
    env._last_action[:] = 0.0
    env._prev_last_action[:] = 0.0
    env._last_joint_vel = env.mjData.qvel[6:].copy()

    print(f"  Set initial state: qpos[:7]={init_qpos[:7]}, joints={init_qpos[7:19]}")
    print(f"  Init qvel (base): {init_qvel[:6]}")

    # Replay trajectory
    if replay_mode == "joint_position":
        frames, env_qpos, env_qvel, actions = replay_joint_position_mode(
            env, traj, max_steps, render_mode=render_mode
        )
    elif replay_mode == "torque":
        frames, env_qpos, env_qvel = replay_torque_mode(
            env, traj, max_steps, render_mode=render_mode
        )
    else:
        raise ValueError(f"Unknown replay_mode: {replay_mode}")

    env.close()

    # Plot comparison
    print("\nPlotting trajectory comparison...")
    plot_trajectory_comparison(traj, env_qpos, replay_mode, max_steps)

    # Animate if we have frames
    if frames and frames[0] is not None:
        print(f"\nCreating animation with {len(frames)} frames...")
        fig_anim = plt.figure(figsize=(10, 8))
        img = plt.imshow(frames[0])
        plt.axis('off')
        plt.title(f"Quadruped Replay ({replay_mode}): {traj_file.name}")

        def animate(i):
            img.set_data(frames[i])
            return [img]

        fps = 1.0 / traj["control_dt"]
        anim = animation.FuncAnimation(
            fig_anim, animate, frames=len(frames),
            interval=1000 / fps, blit=True, repeat=True
        )
        print(f"Animation: {len(frames)} frames at {fps:.1f} FPS")
        plt.show()
    else:
        print("No frames captured (render_mode may not support frame capture).")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Test MPX quadruped trajectories by replaying in the RL environment"
    )
    parser.add_argument(
        "--data-dir", type=str, default="data/quadruped",
        help="Path to directory containing trajectory .npz files (default: data/quadruped)"
    )
    parser.add_argument(
        "--filename", type=str, default=None,
        help="Specific trajectory filename. If not given, randomly selects one."
    )
    parser.add_argument(
        "--max-steps", type=int, default=500,
        help="Maximum control steps to replay (default: 500)"
    )
    parser.add_argument(
        "--replay-mode", type=str, default="joint_position",
        choices=["joint_position", "torque"],
        help="Replay mode: 'joint_position' converts to RL actions, "
             "'torque' directly applies recorded torques (default: joint_position)"
    )
    parser.add_argument(
        "--render-mode", type=str, default="rgb_array",
        choices=["human", "rgb_array", "none"],
        help="Render mode for visualization (default: rgb_array)"
    )

    args = parser.parse_args()

    rm = args.render_mode if args.render_mode != "none" else None

    test_trajectory(
        data_dir=args.data_dir,
        random_select=(args.filename is None),
        filename=args.filename,
        max_steps=args.max_steps,
        replay_mode=args.replay_mode,
        render_mode=rm,
    )