"""
Test DR MPX quadruped trajectory generation by replaying saved trajectories in the RL environment.

This script is the domain-randomized counterpart to gen_traj_data_test_quad.py.
It loads a trajectory .npz file generated by gen_traj_data_mpx_dr.py, restores the
saved startup domain-randomization patch onto QuadrupedVelocityTrackingEnv, and then
replays the recorded torques in the RL environment.

Unlike the nominal test script, this one searches recursively under data/quadruped_dr/
because gen_traj_data_mpx_dr.py saves trajectories in preset-specific subdirectories:

    data/quadruped_dr/<preset>/quadruped_dr_<preset>_seed_*.npz

Usage Examples:

    # Test a random DR trajectory from any preset subdirectory
    python tests/gen_traj_data_test_quad_dr.py --data-dir=data/quadruped_dr

    # Test a random DR trajectory from one preset
    python tests/gen_traj_data_test_quad_dr.py \
        --data-dir=data/quadruped_dr/default_no_push

    # Test a specific file by basename or relative path under data-dir
    python tests/gen_traj_data_test_quad_dr.py --data-dir=data/quadruped_dr \
        --filename="quadruped_dr_default_no_push_seed_000000_ep_1000.npz"
"""

import argparse
from pathlib import Path
import sys
import time

import matplotlib.pyplot as plt
from matplotlib import animation
import mujoco
import numpy as np

# Add repo root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from mpc_rl.envs.domain_randomization import DomainRandomizationConfig
from mpc_rl.envs.velocity_tracking_env import QuadrupedVelocityTrackingEnv

try:
    from tests.gen_traj_data_test_quad import (
        apply_loaded_dr_patch,
        load_trajectory,
        replay_joint_position_mode,
        replay_torque_mode,
    )
except ModuleNotFoundError:
    from gen_traj_data_test_quad import (
        apply_loaded_dr_patch,
        load_trajectory,
        replay_joint_position_mode,
        replay_torque_mode,
    )


def select_trajectory(data_dir, random_select=True, filename=None):
    """Select a DR trajectory file, searching recursively under data_dir."""
    data_dir = Path(data_dir)

    if not data_dir.exists():
        raise FileNotFoundError(f"Data directory not found: {data_dir}")

    traj_files = sorted(data_dir.rglob("*.npz"))

    if len(traj_files) == 0:
        raise FileNotFoundError(f"No .npz files found under {data_dir}")

    if random_select:
        selected = traj_files[np.random.randint(len(traj_files))]
        print(f"Randomly selected: {selected.relative_to(data_dir)}")
        return selected

    if filename is None:
        raise ValueError("filename must be provided when random_select=False")

    filename_path = Path(filename)
    if filename_path.is_absolute():
        if not filename_path.exists():
            raise FileNotFoundError(f"File not found: {filename_path}")
        return filename_path

    direct_match = data_dir / filename_path
    if direct_match.exists():
        return direct_match

    basename_matches = [path for path in traj_files if path.name == filename]
    if len(basename_matches) == 1:
        return basename_matches[0]
    if len(basename_matches) > 1:
        matches = ", ".join(str(path.relative_to(data_dir)) for path in basename_matches)
        raise ValueError(
            f"Filename {filename!r} is ambiguous under {data_dir}. Matches: {matches}"
        )

    raise FileNotFoundError(f"File not found under {data_dir}: {filename}")


def replay_state_mode(env, traj, max_steps, render_mode=None):
    """Replay the saved trajectory by restoring recorded states exactly.

    The DR trajectory files store qpos/qvel at sim frequency but do not store
    MuJoCo's internal solver warm-start state. Re-integrating from qpos/qvel +
    torque therefore accumulates contact-solver drift over time. For visual
    replay and trajectory inspection, restoring the recorded states is exact.
    """
    sim_dt = traj["sim_dt"]
    control_dt = traj["control_dt"]
    decimation = int(round(control_dt / sim_dt))
    qpos_recorded = traj["qpos"]
    qvel_recorded = traj["qvel"]
    commands_recorded = traj["commands"]
    episode_length = traj["episode_length"]

    num_steps = min(episode_length, max_steps)

    frames = []
    env_qpos_history = []
    env_qvel_history = []

    frame = env.render()
    if frame is not None:
        frames.append(frame)

    print(f"Replaying {num_steps} control steps in exact state mode...")

    for ctrl_step in range(num_steps):
        sim_idx_start = ctrl_step * decimation
        sim_idx_end = min((ctrl_step + 1) * decimation, qpos_recorded.shape[1] - 1)

        cmd = commands_recorded[:, sim_idx_start]
        env.set_commands(vx=float(cmd[0]), vy=float(cmd[1]), wz=float(cmd[2]))

        env.mjData.qpos[:] = qpos_recorded[:, sim_idx_end]
        env.mjData.qvel[:] = qvel_recorded[:, sim_idx_end]
        env.mjData.ctrl[:] = 0.0
        mujoco.mj_forward(env.mjModel, env.mjData)

        env_qpos_history.append(env.mjData.qpos.copy())
        env_qvel_history.append(env.mjData.qvel.copy())

        frame = env.render()
        if frame is not None:
            frames.append(frame)
        if render_mode == "human":
            time.sleep(control_dt)

        if (ctrl_step + 1) % 200 == 0:
            print(f"  Step {ctrl_step+1}/{num_steps}")

    return frames, np.array(env_qpos_history), np.array(env_qvel_history)


def plot_trajectory_comparison(traj, env_qpos_history, replay_mode, max_steps):
    """Plot comparison between recorded MPX trajectory and replayed env state."""
    sim_dt = traj["sim_dt"]
    control_dt = traj["control_dt"]
    decimation = int(round(control_dt / sim_dt))
    qpos_recorded = traj["qpos"]
    commands = traj["commands"]
    episode_length = traj["episode_length"]

    num_steps = min(len(env_qpos_history), min(episode_length, max_steps))

    t_ctrl = np.arange(num_steps) * control_dt
    rec_indices = (np.arange(num_steps) + 1) * decimation
    valid_indices = rec_indices[rec_indices < qpos_recorded.shape[1]]
    num_valid = len(valid_indices)
    t_ctrl_valid = t_ctrl[:num_valid]

    fig1, axes1 = plt.subplots(3, 1, figsize=(12, 8), sharex=True)
    base_labels = ["x", "y", "z"]
    for i in range(3):
        rec = qpos_recorded[i, valid_indices]
        env = env_qpos_history[:num_valid, i]
        axes1[i].plot(t_ctrl_valid, rec, "b-", label="recorded", alpha=0.8)
        axes1[i].plot(t_ctrl_valid, env, "r--", label=f"replay ({replay_mode})", alpha=0.8)
        axes1[i].set_ylabel(f"Base {base_labels[i]} (m)")
        axes1[i].legend()
        axes1[i].grid(True)
    axes1[0].set_title("Base Position Comparison")
    axes1[-1].set_xlabel("Time (s)")
    plt.tight_layout()
    plt.show()

    joint_names = [
        "FL_hip", "FL_thigh", "FL_calf",
        "FR_hip", "FR_thigh", "FR_calf",
        "RL_hip", "RL_thigh", "RL_calf",
        "RR_hip", "RR_thigh", "RR_calf",
    ]
    fig2, axes2 = plt.subplots(4, 1, figsize=(12, 10), sharex=True)
    for leg_idx in range(4):
        joint_idx = leg_idx * 3 + 1
        qpos_idx = 7 + joint_idx
        rec = qpos_recorded[qpos_idx, valid_indices]
        env = env_qpos_history[:num_valid, qpos_idx]
        axes2[leg_idx].plot(t_ctrl_valid, rec, "b-", label="recorded", alpha=0.8)
        axes2[leg_idx].plot(t_ctrl_valid, env, "r--", label=f"replay ({replay_mode})", alpha=0.8)
        axes2[leg_idx].set_ylabel(f"{joint_names[joint_idx]} (rad)")
        axes2[leg_idx].legend()
        axes2[leg_idx].grid(True)
    axes2[0].set_title("Thigh Joint Position Comparison (one per leg)")
    axes2[-1].set_xlabel("Time (s)")
    plt.tight_layout()
    plt.show()

    fig3, axes3 = plt.subplots(3, 1, figsize=(12, 6), sharex=True)
    cmd_labels = ["vx (m/s)", "vy (m/s)", "wz (rad/s)"]
    cmd_indices = np.minimum(valid_indices - 1, commands.shape[1] - 1)
    for i in range(3):
        axes3[i].plot(t_ctrl_valid, commands[i, cmd_indices], "g-", linewidth=2)
        axes3[i].set_ylabel(cmd_labels[i])
        axes3[i].grid(True)
    axes3[0].set_title("Velocity Commands During Trajectory")
    axes3[-1].set_xlabel("Time (s)")
    plt.tight_layout()
    plt.show()

    fig4, ax4 = plt.subplots(figsize=(12, 4))
    errors = []
    for step in range(num_valid):
        rec_joints = qpos_recorded[7:19, valid_indices[step]]
        env_joints = env_qpos_history[step, 7:19]
        errors.append(np.linalg.norm(rec_joints - env_joints))
    ax4.plot(t_ctrl_valid, errors, "k-")
    ax4.set_xlabel("Time (s)")
    ax4.set_ylabel("Joint position error (L2 norm, rad)")
    ax4.set_title("Joint Position Tracking Error")
    ax4.grid(True)
    plt.tight_layout()
    plt.show()


def test_trajectory(
    data_dir,
    random_select=True,
    filename=None,
    max_steps=500,
    replay_mode="state",
    render_mode="rgb_array",
):
    """Test a saved DR MPX trajectory by replaying it in the RL environment."""
    traj_file = select_trajectory(data_dir, random_select=random_select, filename=filename)
    print(f"\nLoading trajectory from: {traj_file}")
    traj = load_trajectory(traj_file)

    if traj["dr_patch"] is None:
        raise ValueError(
            "Selected trajectory does not contain a saved startup DR patch. "
            "Use tests/gen_traj_data_test_quad.py for nominal trajectories."
        )

    print(f"  Seed: {traj['seed']}")
    print(f"  Episode length: {traj['episode_length']} control steps")
    print(f"  qpos shape: {traj['qpos'].shape}")
    print(f"  qvel shape: {traj['qvel'].shape}")
    print(f"  sim_dt: {traj['sim_dt']}s, control_dt: {traj['control_dt']}s")
    print(f"  default_joint_pos: {traj['default_joint_pos']}")
    print(f"  action_scale: {traj['action_scale']}")
    print(f"  DR preset: {traj['dr_patch'].get('dr_config_type', 'unknown')}")
    print(f"  DR seed: {traj['dr_patch'].get('dr_seed', 'unknown')}")
    print(f"  DR fields: {traj['dr_patch'].get('dr_applied_fields', np.array([])).tolist()}")

    print("\nCreating QuadrupedVelocityTrackingEnv (DR disabled, then applying saved patch)...")
    env = QuadrupedVelocityTrackingEnv(
        robot="go2",
        scene="flat",
        render_mode=render_mode,
        domain_rand_cfg=DomainRandomizationConfig(enable=False, push_robots=False),
    )

    env.max_pitch = np.pi
    env.max_roll = np.pi
    env.min_base_height = -1.0

    env.reset(seed=42)
    apply_loaded_dr_patch(env, traj["dr_patch"])

    init_qpos = traj["qpos"][:, 0]
    init_qvel = traj["qvel"][:, 0]

    env.mjData.qpos[:] = init_qpos
    env.mjData.qvel[:] = init_qvel
    env.mjData.ctrl[:] = 0.0
    env.mjData.qacc_warmstart[:] = 0.0
    mujoco.mj_forward(env.mjModel, env.mjData)

    env._last_action[:] = 0.0
    env._prev_last_action[:] = 0.0
    env._last_joint_vel = env.mjData.qvel[6:].copy()

    print(f"  Set initial state: qpos[:7]={init_qpos[:7]}, joints={init_qpos[7:19]}")
    print(f"  Init qvel (base): {init_qvel[:6]}")

    if replay_mode == "state":
        frames, env_qpos, env_qvel = replay_state_mode(
            env, traj, max_steps, render_mode=render_mode
        )
    elif replay_mode == "joint_position":
        frames, env_qpos, env_qvel, actions = replay_joint_position_mode(
            env, traj, max_steps, render_mode=render_mode
        )
    elif replay_mode == "torque":
        frames, env_qpos, env_qvel = replay_torque_mode(
            env, traj, max_steps, render_mode=render_mode
        )
    else:
        raise ValueError(f"Unknown replay_mode: {replay_mode}")

    env.close()

    print("\nPlotting trajectory comparison...")
    plot_trajectory_comparison(traj, env_qpos, replay_mode, max_steps)

    if frames and frames[0] is not None:
        print(f"\nCreating animation with {len(frames)} frames...")
        fig_anim = plt.figure(figsize=(10, 8))
        img = plt.imshow(frames[0])
        plt.axis("off")
        plt.title(f"Quadruped DR Replay ({replay_mode}): {traj_file.name}")

        def animate(i):
            img.set_data(frames[i])
            return [img]

        fps = 1.0 / traj["control_dt"]
        anim = animation.FuncAnimation(
            fig_anim,
            animate,
            frames=len(frames),
            interval=1,
            blit=True,
            repeat=True,
        )
        print(f"Animation: {len(frames)} frames at {fps:.1f} FPS")
        plt.show()
    else:
        print("No frames captured (render_mode may not support frame capture).")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Test DR MPX quadruped trajectories by replaying in the RL environment"
    )
    parser.add_argument(
        "--data-dir",
        type=str,
        default="data/quadruped_dr",
        help="Path to trajectory root (searched recursively, default: data/quadruped_dr)",
    )
    parser.add_argument(
        "--filename",
        type=str,
        default=None,
        help="Specific filename or relative path under data-dir. If omitted, selects randomly.",
    )
    parser.add_argument(
        "--max-steps",
        type=int,
        default=500,
        help="Maximum control steps to replay (default: 500)",
    )
    parser.add_argument(
        "--replay-mode",
        type=str,
        default="state",
        choices=["state", "joint_position", "torque"],
        help="Replay mode: 'state' is exact saved-state playback; "
             "'joint_position' and 'torque' re-integrate dynamics (default: state)",
    )
    parser.add_argument(
        "--render-mode",
        type=str,
        default="rgb_array",
        choices=["human", "rgb_array", "none"],
        help="Render mode for visualization (default: rgb_array)",
    )

    args = parser.parse_args()
    rm = args.render_mode if args.render_mode != "none" else None

    test_trajectory(
        data_dir=args.data_dir,
        random_select=(args.filename is None),
        filename=args.filename,
        max_steps=args.max_steps,
        replay_mode=args.replay_mode,
        render_mode=rm,
    )
