"""
Test MPX quadruped trajectory generation by replaying saved trajectories in the RL environment.

This script loads a trajectory .npz file generated by gen_traj_data_mpx.py and replays it
in QuadrupedVelocityTrackingEnv to verify correctness. It converts the recorded joint
positions from MPX to RL actions (joint position residuals) and compares the resulting
trajectory with the original.

NOTE: Because the PD gains differ between MPX (kp=10, kd=2 uniform) and the RL env
(kp=[20,20,40,...], kd=[1,1,2,...] per-joint), the replayed trajectory will diverge
from the recorded one. This is expected and documented.

Usage Examples:

    # Test a random trajectory from the default directory
    python tests/gen_traj_data_test_quad.py --data-dir=data/quadruped

    # Test a specific trajectory file
    python tests/gen_traj_data_test_quad.py --data-dir=data/quadruped \
        --filename="quadruped_seed_000000_ep_1000.npz"

    # Limit visualization to 200 control steps
    python tests/gen_traj_data_test_quad.py --data-dir=data/quadruped --max-steps=200

    # Use torque replay mode instead of joint position replay
    python tests/gen_traj_data_test_quad.py --data-dir=data/quadruped --replay-mode=torque
"""

import time
import numpy as np
import argparse
from pathlib import Path
import sys

import mujoco
import matplotlib.pyplot as plt
from matplotlib import animation

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from mpc_rl.envs.velocity_tracking_env import QuadrupedVelocityTrackingEnv
from mpc_rl.envs.domain_randomization import DomainRandomizationConfig


def select_trajectory(data_dir, random_select=True, filename=None):
    """Select a trajectory file from the data directory."""
    data_dir = Path(data_dir)

    if not data_dir.exists():
        raise FileNotFoundError(f"Data directory not found: {data_dir}")

    traj_files = sorted(data_dir.glob("*.npz"))

    if len(traj_files) == 0:
        raise FileNotFoundError(f"No .npz files found in {data_dir}")

    if random_select:
        selected = traj_files[np.random.randint(len(traj_files))]
        print(f"Randomly selected: {selected.name}")
    else:
        if filename is None:
            raise ValueError("filename must be provided when random_select=False")
        selected = data_dir / filename
        if not selected.exists():
            raise FileNotFoundError(f"File not found: {selected}")

    return selected


def load_trajectory(traj_file):
    """Load and parse an MPX quadruped trajectory file.

    Returns:
        dict with parsed trajectory data.
    """
    data = np.load(traj_file, allow_pickle=True)

    result = {
        "qpos": data["qpos"],                      # (nq, T+1)
        "qvel": data["qvel"],                      # (nv, T+1)
        "tau_applied": data["tau_applied"],         # (n_joints, T)
        "tau_mpx": data["tau_mpx"],                 # (n_joints, T)
        "q_des": data["q_des"],                     # (n_joints, T)
        "time": data["time"],                       # (T+1,)
        "commands": data["commands"],               # (3, T)
        "seed": int(data["seed"]),
        "default_joint_pos": data["default_joint_pos"],
        "action_scale": float(data["action_scale"]),
        "sim_dt": float(data["sim_dt"]),
        "control_dt": float(data["control_dt"]),
        "episode_length": int(data["episode_length"]),
    }
    return result


def replay_joint_position_mode(env, traj, max_steps, render_mode=None):
    """Replay trajectory using inverse PD to convert MPX outputs to RL actions.

    When the env's PD gains match the MPX feedback gains (kp=10, kd=2), the
    inverse PD simplifies to a state-independent formula:
        q_target = q_des + tau_mpx / kp
    This exactly reproduces the MPX control law at every substep within the
    decimation, giving near-perfect tracking.

    When gains don't match, falls back to the general inverse PD using the
    total recorded torque and current env state.

    Args:
        env: QuadrupedVelocityTrackingEnv instance (already initialized to start state).
        traj: Parsed trajectory data dict.
        max_steps: Maximum control steps to replay.
        render_mode: Render mode string. When "human", sleeps between frames
            to maintain real-time playback speed.

    Returns:
        Tuple of (frames, env_qpos_history, env_qvel_history, actions_applied).
    """
    sim_dt = traj["sim_dt"]
    control_dt = traj["control_dt"]
    decimation = int(round(control_dt / sim_dt))  # 4
    default_joint_pos = traj["default_joint_pos"]
    q_des_recorded = traj["q_des"]
    tau_mpx_recorded = traj["tau_mpx"]
    tau_applied = traj["tau_applied"]
    commands_recorded = traj["commands"]
    episode_length = traj["episode_length"]

    # Use env's actual action_scale and PD gains (must match what step() uses)
    action_scale = env.action_scale
    kp = env.kp
    kd = env.kd

    # Check if gains match MPX (kp=10, kd=2 uniform) for the exact formula
    mpx_kp, mpx_kd = 10.0, 2.0
    gains_match = np.allclose(kp, mpx_kp) and np.allclose(kd, mpx_kd)

    num_steps = min(episode_length, max_steps)

    frames = []
    env_qpos_history = []
    env_qvel_history = []
    actions_applied = []
    rewards = []
    clip_count = 0

    # Get initial frame
    frame = env.render()
    if frame is not None:
        frames.append(frame)

    mode_label = "matched-gain" if gains_match else "general inverse PD"
    print(f"Replaying {num_steps} control steps in joint-position mode ({mode_label})...")

    for ctrl_step in range(num_steps):
        sim_idx = ctrl_step * decimation

        if gains_match:
            # Gains match MPX: q_target = q_des + tau_mpx / kp
            # This reproduces the exact MPX control law at all substeps.
            q_des = q_des_recorded[:, sim_idx]
            tau_mpx = tau_mpx_recorded[:, sim_idx]
            q_target = q_des + tau_mpx / kp
        else:
            # General inverse PD: match torque at first substep only.
            q_current = env.mjData.qpos[7:19].copy()
            dq_current = env.mjData.qvel[6:18].copy()
            tau_desired = tau_applied[:, sim_idx]
            q_target = q_current + (tau_desired + kd * dq_current) / kp

        # Convert to RL action
        action = (q_target - default_joint_pos) / action_scale
        raw_action = action.copy()
        action = np.clip(action, -1.0, 1.0)

        if np.any(np.abs(raw_action) > 1.0):
            clip_count += 1

        # Set velocity commands to match what MPX was tracking
        cmd = commands_recorded[:, sim_idx]
        env.set_commands(vx=cmd[0], vy=cmd[1], wz=cmd[2])

        # Step the RL environment
        obs, reward, terminated, truncated, info = env.step(action)

        # Record
        env_qpos_history.append(env.mjData.qpos.copy())
        env_qvel_history.append(env.mjData.qvel.copy())
        actions_applied.append(action.copy())
        rewards.append(reward)

        frame = env.render()
        if frame is not None:
            frames.append(frame)
        if render_mode == "human":
            time.sleep(sim_dt)

        if terminated or truncated:
            print(f"  Episode ended at step {ctrl_step+1}/{num_steps} "
                  f"(terminated={terminated}, truncated={truncated})")
            break

        if (ctrl_step + 1) % 200 == 0:
            print(f"  Step {ctrl_step+1}/{num_steps}, reward={reward:.4f}")

    env_qpos_history = np.array(env_qpos_history)  # (steps, nq)
    env_qvel_history = np.array(env_qvel_history)  # (steps, nv)
    actions_applied = np.array(actions_applied)     # (steps, n_joints)

    print(f"  Total reward: {sum(rewards):.2f}, mean: {np.mean(rewards):.4f}")
    if clip_count > 0:
        print(f"  Warning: action clipped at {clip_count}/{len(rewards)} steps")

    return frames, env_qpos_history, env_qvel_history, actions_applied


def replay_torque_mode(env, traj, max_steps, render_mode=None):
    """Replay trajectory by directly applying recorded torques.

    Bypasses the RL env's PD controller by directly setting torques from
    the MPX trajectory. This gives the closest match to the original trajectory.

    Args:
        env: QuadrupedVelocityTrackingEnv instance (already initialized to start state).
        traj: Parsed trajectory data dict.
        max_steps: Maximum control steps to replay.
        render_mode: Render mode string. When "human", sleeps between frames
            to maintain real-time playback speed.

    Returns:
        Tuple of (frames, env_qpos_history, env_qvel_history).
    """
    sim_dt = traj["sim_dt"]
    control_dt = traj["control_dt"]
    decimation = int(round(control_dt / sim_dt))  # 4
    tau_applied = traj["tau_applied"]
    commands_recorded = traj["commands"]
    episode_length = traj["episode_length"]
    total_sim_steps = tau_applied.shape[1]

    num_ctrl_steps = min(episode_length, max_steps)
    num_sim_steps = num_ctrl_steps * decimation

    frames = []
    env_qpos_history = []
    env_qvel_history = []

    frame = env.render()
    if frame is not None:
        frames.append(frame)

    print(f"Replaying {num_ctrl_steps} control steps in torque mode...")

    for sim_step in range(min(num_sim_steps, total_sim_steps)):
        # Directly apply the recorded torques to MuJoCo
        torques = tau_applied[:, sim_step]
        env.mjData.ctrl[:] = torques
        mujoco.mj_step(env.mjModel, env.mjData)

        # Record at control frequency
        if (sim_step + 1) % decimation == 0:
            env_qpos_history.append(env.mjData.qpos.copy())
            env_qvel_history.append(env.mjData.qvel.copy())

            frame = env.render()
            if frame is not None:
                frames.append(frame)
            if render_mode == "human":
                time.sleep(control_dt)

            ctrl_step = (sim_step + 1) // decimation
            if ctrl_step % 200 == 0:
                print(f"  Step {ctrl_step}/{num_ctrl_steps}")

    env_qpos_history = np.array(env_qpos_history)
    env_qvel_history = np.array(env_qvel_history)

    return frames, env_qpos_history, env_qvel_history


def plot_trajectory_comparison(traj, env_qpos_history, replay_mode, max_steps):
    """Plot comparison between recorded MPX trajectory and RL env replay.

    Shows joint positions, base position/orientation, and base velocities.
    """
    sim_dt = traj["sim_dt"]
    control_dt = traj["control_dt"]
    decimation = int(round(control_dt / sim_dt))
    qpos_recorded = traj["qpos"]
    qvel_recorded = traj["qvel"]
    time_recorded = traj["time"]
    commands = traj["commands"]
    episode_length = traj["episode_length"]

    num_steps = min(len(env_qpos_history), min(episode_length, max_steps))

    # Build time axes
    t_ctrl = np.arange(num_steps) * control_dt
    # Recorded at control frequency (downsample from sim)
    rec_indices = np.arange(num_steps) * decimation
    valid_indices = rec_indices[rec_indices < qpos_recorded.shape[1]]
    num_valid = len(valid_indices)
    t_ctrl_valid = t_ctrl[:num_valid]

    # -- 1) Base position (x, y, z) --
    fig1, axes1 = plt.subplots(3, 1, figsize=(12, 8), sharex=True)
    base_labels = ["x", "y", "z"]
    for i in range(3):
        rec = qpos_recorded[i, valid_indices]
        env = env_qpos_history[:num_valid, i]
        axes1[i].plot(t_ctrl_valid, rec, 'b-', label='MPX recorded', alpha=0.8)
        axes1[i].plot(t_ctrl_valid, env, 'r--', label=f'RL replay ({replay_mode})', alpha=0.8)
        axes1[i].set_ylabel(f"Base {base_labels[i]} (m)")
        axes1[i].legend()
        axes1[i].grid(True)
    axes1[0].set_title("Base Position Comparison")
    axes1[-1].set_xlabel("Time (s)")
    plt.tight_layout()
    plt.show()

    # -- 2) Joint positions (first 4 joints: one per leg) --
    joint_names = [
        "FL_hip", "FL_thigh", "FL_calf",
        "FR_hip", "FR_thigh", "FR_calf",
        "RL_hip", "RL_thigh", "RL_calf",
        "RR_hip", "RR_thigh", "RR_calf",
    ]
    fig2, axes2 = plt.subplots(4, 1, figsize=(12, 10), sharex=True)
    for leg_idx in range(4):
        joint_idx = leg_idx * 3 + 1  # thigh joint of each leg
        qpos_idx = 7 + joint_idx
        rec = qpos_recorded[qpos_idx, valid_indices]
        env = env_qpos_history[:num_valid, qpos_idx]
        axes2[leg_idx].plot(t_ctrl_valid, rec, 'b-', label='MPX recorded', alpha=0.8)
        axes2[leg_idx].plot(t_ctrl_valid, env, 'r--', label=f'RL replay ({replay_mode})', alpha=0.8)
        axes2[leg_idx].set_ylabel(f"{joint_names[joint_idx]} (rad)")
        axes2[leg_idx].legend()
        axes2[leg_idx].grid(True)
    axes2[0].set_title("Thigh Joint Position Comparison (one per leg)")
    axes2[-1].set_xlabel("Time (s)")
    plt.tight_layout()
    plt.show()

    # -- 3) Velocity commands --
    fig3, axes3 = plt.subplots(3, 1, figsize=(12, 6), sharex=True)
    cmd_labels = ["vx (m/s)", "vy (m/s)", "wz (rad/s)"]
    for i in range(3):
        # Commands at sim frequency, downsample to control frequency
        cmd_vals = commands[i, valid_indices]
        axes3[i].plot(t_ctrl_valid, cmd_vals, 'g-', linewidth=2)
        axes3[i].set_ylabel(cmd_labels[i])
        axes3[i].grid(True)
    axes3[0].set_title("Velocity Commands During Trajectory")
    axes3[-1].set_xlabel("Time (s)")
    plt.tight_layout()
    plt.show()

    # -- 4) Joint position error over time --
    fig4, ax4 = plt.subplots(figsize=(12, 4))
    errors = []
    for step in range(num_valid):
        rec_joints = qpos_recorded[7:19, valid_indices[step]]
        env_joints = env_qpos_history[step, 7:19]
        errors.append(np.linalg.norm(rec_joints - env_joints))
    ax4.plot(t_ctrl_valid, errors, 'k-')
    ax4.set_xlabel("Time (s)")
    ax4.set_ylabel("Joint position error (L2 norm, rad)")
    ax4.set_title("Joint Position Tracking Error (MPX vs RL replay)")
    ax4.grid(True)
    plt.tight_layout()
    plt.show()


def _match_generation_friction(env, tangential=0.7, torsional=0.005, rolling=0.0):
    """Set floor and foot geom friction to match the generation environment.

    QuadrupedEnv._set_ground_friction() applies the same friction values to
    floor-like geoms and foot geoms. Replicate that here so the RL env's
    contact dynamics match exactly.
    """
    friction = np.array([tangential, torsional, rolling])
    floor_names = {"ground", "floor", "hfield", "terrain"}

    foot_geom_ids = set(env._foot_geom_ids.values())

    for geom_id in range(env.mjModel.ngeom):
        geom_name = mujoco.mj_id2name(
            env.mjModel, mujoco.mjtObj.mjOBJ_GEOM, geom_id
        )
        if (geom_name and geom_name.lower() in floor_names) or geom_id in foot_geom_ids:
            env.mjModel.geom_friction[geom_id, :] = friction


def test_trajectory(data_dir, random_select=True, filename=None,
                    max_steps=500, replay_mode="joint_position",
                    render_mode="rgb_array"):
    """Test a saved MPX trajectory by replaying it in the RL environment.

    Args:
        data_dir: Path to directory containing trajectory .npz files.
        random_select: If True, randomly select a trajectory file.
        filename: Specific filename to load.
        max_steps: Maximum control steps to replay.
        replay_mode: "joint_position" or "torque".
        render_mode: Render mode for the environment.
    """
    # Select and load trajectory
    traj_file = select_trajectory(data_dir, random_select=random_select, filename=filename)
    print(f"\nLoading trajectory from: {traj_file}")
    traj = load_trajectory(traj_file)

    print(f"  Seed: {traj['seed']}")
    print(f"  Episode length: {traj['episode_length']} control steps")
    print(f"  qpos shape: {traj['qpos'].shape}")
    print(f"  qvel shape: {traj['qvel'].shape}")
    print(f"  sim_dt: {traj['sim_dt']}s, control_dt: {traj['control_dt']}s")
    print(f"  default_joint_pos: {traj['default_joint_pos']}")
    print(f"  action_scale: {traj['action_scale']}")

    # For joint_position replay, use MPX-matching PD gains (kp=10, kd=2 uniform)
    # so the PD controller exactly reproduces the MPX control law at every substep.
    # Also use a wider action_scale so q_target = q_des + tau_mpx/kp fits in [-1, 1].
    replay_kp = 10.0 if replay_mode == "joint_position" else None
    replay_kd = 2.0 if replay_mode == "joint_position" else None
    replay_action_scale = 4.0 if replay_mode == "joint_position" else 0.5

    # Create RL environment with domain randomization disabled so that
    # the MuJoCo model matches the generation environment exactly.
    print(f"\nCreating QuadrupedVelocityTrackingEnv (DR disabled)...")
    env = QuadrupedVelocityTrackingEnv(
        robot="go2",
        scene="flat",
        render_mode=render_mode,
        kp=replay_kp,
        kd=replay_kd,
        action_scale=replay_action_scale,
        domain_rand_cfg=DomainRandomizationConfig(enable=False, push_robots=False),
    )

    # Match ground friction to the generation environment.
    # gen_traj_data_mpx.py creates QuadrupedEnv with ground_friction_coeff=0.7,
    # which sets friction to [0.7, 0.005, 0.0] on the floor and all foot geoms.
    _match_generation_friction(env, tangential=0.7, torsional=0.005, rolling=0.0)

    # Disable early termination during replay so we can observe the full
    # trajectory even if small errors accumulate. The replay is diagnostic,
    # not training, so termination thresholds should be permissive.
    env.max_pitch = np.pi
    env.max_roll = np.pi
    env.min_base_height = -1.0

    # Reset the environment
    obs, info = env.reset(seed=42)

    # Set the initial state from the recorded trajectory
    init_qpos = traj["qpos"][:, 0]
    init_qvel = traj["qvel"][:, 0]

    env.mjData.qpos[:] = init_qpos
    env.mjData.qvel[:] = init_qvel
    env.mjData.ctrl[:] = 0.0
    env.mjData.qacc_warmstart[:] = 0.0
    mujoco.mj_forward(env.mjModel, env.mjData)

    # Reset internal tracking state after setting initial state
    env._last_action[:] = 0.0
    env._prev_last_action[:] = 0.0
    env._last_joint_vel = env.mjData.qvel[6:].copy()

    print(f"  Set initial state: qpos[:7]={init_qpos[:7]}, joints={init_qpos[7:19]}")
    print(f"  Init qvel (base): {init_qvel[:6]}")

    # Replay trajectory
    if replay_mode == "joint_position":
        frames, env_qpos, env_qvel, actions = replay_joint_position_mode(
            env, traj, max_steps, render_mode=render_mode
        )
    elif replay_mode == "torque":
        frames, env_qpos, env_qvel = replay_torque_mode(
            env, traj, max_steps, render_mode=render_mode
        )
    else:
        raise ValueError(f"Unknown replay_mode: {replay_mode}")

    env.close()

    # Plot comparison
    print("\nPlotting trajectory comparison...")
    plot_trajectory_comparison(traj, env_qpos, replay_mode, max_steps)

    # Animate if we have frames
    if frames and frames[0] is not None:
        print(f"\nCreating animation with {len(frames)} frames...")
        fig_anim = plt.figure(figsize=(10, 8))
        img = plt.imshow(frames[0])
        plt.axis('off')
        plt.title(f"Quadruped Replay ({replay_mode}): {traj_file.name}")

        def animate(i):
            img.set_data(frames[i])
            return [img]

        fps = 1.0 / traj["control_dt"]
        anim = animation.FuncAnimation(
            fig_anim, animate, frames=len(frames),
            interval=1000 / fps, blit=True, repeat=True
        )
        print(f"Animation: {len(frames)} frames at {fps:.1f} FPS")
        plt.show()
    else:
        print("No frames captured (render_mode may not support frame capture).")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Test MPX quadruped trajectories by replaying in the RL environment"
    )
    parser.add_argument(
        "--data-dir", type=str, default="data/quadruped",
        help="Path to directory containing trajectory .npz files (default: data/quadruped)"
    )
    parser.add_argument(
        "--filename", type=str, default=None,
        help="Specific trajectory filename. If not given, randomly selects one."
    )
    parser.add_argument(
        "--max-steps", type=int, default=500,
        help="Maximum control steps to replay (default: 500)"
    )
    parser.add_argument(
        "--replay-mode", type=str, default="joint_position",
        choices=["joint_position", "torque"],
        help="Replay mode: 'joint_position' converts to RL actions, "
             "'torque' directly applies recorded torques (default: joint_position)"
    )
    parser.add_argument(
        "--render-mode", type=str, default="rgb_array",
        choices=["human", "rgb_array", "none"],
        help="Render mode for visualization (default: rgb_array)"
    )

    args = parser.parse_args()

    rm = args.render_mode if args.render_mode != "none" else None

    test_trajectory(
        data_dir=args.data_dir,
        random_select=(args.filename is None),
        filename=args.filename,
        max_steps=args.max_steps,
        replay_mode=args.replay_mode,
        render_mode=rm,
    )
