"""
Test script to try out MPC injection callback with custom SAC training.

Mainly here to experiment with before integration into the main training script.
"""

import datetime
import json
import os
from pathlib import Path
import warnings
import subprocess

# Configure JAX for GPU with compatible architecture settings
# Try to detect GPU first
gpu_available = False
try:
    # Get GPU compute capability
    result = subprocess.run(
        ["nvidia-smi", "--query-gpu=compute_cap", "--format=csv,noheader"],
        capture_output=True, text=True, check=True
    )
    compute_cap = result.stdout.strip().split('\n')[0].replace('.', '')
    print(f"Detected GPU compute capability: {compute_cap}")
    
    # Configure for GPU
    os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"
    os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"] = "platform"
    os.environ["JAX_PLATFORMS"] = "cuda"
    os.environ["XLA_FLAGS"] = f"--xla_gpu_cuda_data_dir=/usr/lib/cuda"
    gpu_available = True
except Exception as e:
    print(f"Could not detect GPU compute capability: {e}")
    print("Falling back to CPU")
    # Configure for CPU
    os.environ["JAX_PLATFORMS"] = "cpu"

# Suppress JAX warnings and info logs
warnings.filterwarnings("ignore", category=UserWarning, module="jax")
warnings.filterwarnings("ignore", category=FutureWarning, module="jax")

from absl import app
from absl import flags
from absl import logging

import gymnasium as gym
from dm_control import suite
from shimmy import DmControlCompatibilityV0
from gymnasium.wrappers import FlattenObservation
import matplotlib.pyplot as plt
from matplotlib import animation
import numpy as np
import mediapy as media
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.callbacks import CheckpointCallback, EvalCallback
from stable_baselines3.common.evaluation import evaluate_policy
import sys

# Add parent directory to path to import from mpc_rl
sys.path.insert(0, str(Path(__file__).parent.parent))

from mpc_rl.planner.mpc_planner import MPCPlanner
from mpc_rl.common import FixedMPCInjectCallback, AdaptiveMPCInjectCallback
from mpc_rl.sac_mpc import SAC_MPC

# Import JAX and verify backend
import jax
print(f"JAX backend: {jax.default_backend()}")
print(f"JAX devices: {jax.devices()}")

# Inform user about the backend being used
if jax.default_backend() == 'gpu':
    print("JAX is using GPU acceleration")
elif jax.default_backend() == 'cpu':
    print("JAX is using CPU (GPU not available or not detected)")
else:
    print(f"JAX is using backend: {jax.default_backend()}")

# Set logging level to suppress JAX backend initialization messages
logging.set_verbosity(logging.WARNING)


def make_dmc_env(domain: str, task: str, render_mode=None):
        dm_env = suite.load(domain_name=domain, task_name=task)
        gym_env = DmControlCompatibilityV0(dm_env, render_mode=render_mode)
        gym_env = FlattenObservation(gym_env)
        return gym_env


if __name__ == "__main__":
    print("Testing if SAC-MPC working...")

    # Setup Environment
    domain = "cartpole"
    task = "swingup"

    vec_env = make_vec_env(
        lambda: make_dmc_env(domain, task), # lambda fxn so make_vec_env() can make multiple envs
        n_envs=4,
        seed=1,
    )

    # VecNormalize standardizes observations and rewards to N(0,1), which is critical for stable
    # training (prevents different scale features from dominating)
    vec_env = VecNormalize(vec_env, norm_obs=True, norm_reward=True)

    # Setup Model
    model = SAC_MPC(
        "MlpPolicy",
        vec_env,
        learning_rate=3e-4,
        buffer_size=1_000_000, # og 1_000_000
        learning_starts=10000,
        batch_size=256,
        tau=0.005,
        gamma=0.99,
        verbose=1,  # Enable training logs (0=no output, 1=info, 2=debug)
        seed=1,
    )

    # Setup MPC injection callback
    # You can choose one of the following modes:
    
    # MODE 1: Load pre-generated trajectories from data/ directory (RECOMMENDED)
    # This uses the trajectories generated by gen_traj_data.py
    print("\nSetting up MPC Injection from pre-generated trajectories...")
    inject_callback = FixedMPCInjectCallback(
        inject_every_n_timesteps=5000,    # Inject after every 5,000 timesteps
        num_mpc_trajectories=10,          # Load 10 trajectories each time
        data_dir="data/cartpole_0_001dt/",# Directory with saved trajectories
        random_select=True,               # Randomly select trajectories
        verbose=1                         # Show injection progress
    )
    
    # MODE 2: Generate trajectories on-the-fly with MPC planner
    # Uncomment this block to use on-the-fly generation instead
    """
    print("\nSetting up MPC Planner for on-the-fly trajectory generation...")
    planner = MPCPlanner(
        rollout_horizon=10000,  # 10 seconds at 0.001s timestep for sim (0.01 for planner)
        opt_steps=10,
        weights={ # Default from mjpc's gui
            "Vertical": 10.0,
            "Centered": 10.0,
            "Velocity": 0.1,
            "Control": 0.1
        },
        task_params={"Goal": 0.0}, # Target cart position, note that this varies with env and task
        init_state_noise_flag=True,  # Enable noise for diverse trajectories
        qpos_noise_rnge=(-0.02, 0.02),
        qvel_noise_rnge=(-0.02, 0.02)
    )
    
    inject_callback = FixedMPCInjectCallback(
        mpc_planner=planner,
        inject_every_n_timesteps=5000,  # Inject after every 5,000 timesteps
        num_mpc_trajectories=10,        # Generate 10 MPC traj each time
        verbose=1                       # Show injection progress
    )
    """
    
    # MODE 3: Load specific trajectory files (for controlled experiments)
    # Uncomment this block to use specific trajectories
    """
    print("\nSetting up MPC Injection from specific trajectory files...")
    inject_callback = FixedMPCInjectCallback(
        inject_every_n_timesteps=5000,
        num_mpc_trajectories=3,
        data_dir="data/cartpole_0_001dt/",
        random_select=False,
        trajectory_files=[
            "qpos_[0.00,3.14]_qvel_[0.00,0.00]_rh_10000.npz",
            "qpos_[0.50,3.14]_qvel_[0.50,0.50]_rh_10000.npz",
            "qpos_[-0.50,3.14]_qvel_[-0.50,-0.50]_rh_10000.npz"
        ],
        verbose=1
    )
    """

    # Create eval environment for evaluation callback
    # Must be wrapped the same way as training env (with VecNormalize)
    eval_env = make_vec_env(
        lambda: make_dmc_env(domain, task),
        n_envs=1,
        seed=2,
    )
    eval_env = VecNormalize(
        eval_env,
        training=False,  # Don't update stats during evaluation
        norm_obs=True,
        norm_reward=True,
    )

    # Create callback for evaluating the trained model
    # This will evaluate the model periodically during training
    eval_callback = EvalCallback(
        eval_env,
        best_model_save_path=None,  # Don't save best model for this test
        log_path=None,  # Don't save eval logs for this test
        eval_freq=10_000,  # Evaluate every 10k steps
        deterministic=True,
        render=False,
        n_eval_episodes=5,
        verbose=0,
    )

    print("\nStarting training...")
    print(f"Training environment: {vec_env.num_envs} parallel environments")
    
    # Train the model with both eval and MPC injection callbacks
    model.learn(
        total_timesteps=500_000,
        callback=[eval_callback, inject_callback],  # Include MPC injection callback
        log_interval=10,  # Log training metrics every 10 episodes
        progress_bar=True,
    )
    
    print("\nTraining complete!")
    
    # Print MPC injection statistics
    print(f"\n{'='*60}")
    print("MPC Injection Statistics:")
    print(f"  Total injections: {inject_callback.total_injections}")
    print(f"  Total timesteps: {inject_callback.num_timesteps}")
    print(f"  Trajectories per injection: {inject_callback.num_mpc_trajectories}")
    print(f"  Total MPC trajectories injected: {inject_callback.total_injections * inject_callback.num_mpc_trajectories}")
    print(f"{'='*60}\n")
    
    # Final evaluation with the trained model
    print("\nRunning final evaluation...")
    
    mean_reward, std_reward = evaluate_policy(
        model,
        eval_env,
        n_eval_episodes=10,
        deterministic=True,
        render=False,
    )
    
    print(f"\nFinal Evaluation Results:")
    print(f"Mean reward: {mean_reward:.2f} +/- {std_reward:.2f}")
    
    # Create visualization of final policy performance
    print("\nGenerating performance visualization...")
    
    # Create a single non-vectorized environment for visualization
    # IMPORTANT: Must use VecNormalize with the same statistics as training!
    vis_env_raw = make_vec_env(lambda: make_dmc_env(domain, task, render_mode="rgb_array"), n_envs=1)
    vis_env = VecNormalize(vis_env_raw, training=False, norm_obs=True, norm_reward=False)
    # Copy normalization statistics from training environment
    vis_env.obs_rms = vec_env.obs_rms
    vis_env.ret_rms = vec_env.ret_rms
    
    # Get the timestep from the environment
    dt = vis_env.unwrapped.envs[0].unwrapped._env.physics.timestep()
    print(f"Environment timestep: {dt} seconds")
    
    # Run one episode and collect data
    obs = vis_env.reset()
    
    # Storage for trajectories
    # DM Control cartpole swingup has a 10 second time limit
    # With control timestep of 0.01s, this gives 1000 max steps
    max_steps = 1000
    observations = []
    actions = []
    rewards = []
    times = []
    frames = []
    
    done = False
    truncated = False
    step = 0
    
    while not done and not truncated and step < max_steps:
        # Get action from policy
        action, _states = model.predict(obs, deterministic=True)
        
        # Store data
        observations.append(obs[0])  # Extract from vectorized format
        actions.append(action[0])    # Extract from vectorized format
        times.append(step * dt)
        
        # Render frame
        frame = vis_env.render(mode='rgb_array')
        frames.append(frame)
        
        # Step environment (VecEnv returns different format)
        obs, reward, done_vec, info = vis_env.step(action)
        done = done_vec[0]
        truncated = info[0].get('TimeLimit.truncated', False)
        rewards.append(reward[0])
        
        step += 1
        
        if step % 500 == 0:
            print(f"Visualization step: {step}")
    
    # Convert to numpy arrays
    observations = np.array(observations)
    actions = np.array(actions)
    rewards = np.array(rewards)
    times = np.array(times)
    
    print(f"Episode completed: {step} steps, total time: {times[-1]:.2f} seconds")
    print(f"Total reward: {np.sum(rewards):.2f}")
    
    # Create plots similar to mjpc_ex.py
    # The dm_control cartpole swingup observation space is:
    # [cart_position, cos(pole_angle), sin(pole_angle), cart_velocity, pole_angular_velocity]
    cart_pos = observations[:, 0]
    cos_angle = observations[:, 1]
    sin_angle = observations[:, 2]
    cart_vel = observations[:, 3]
    pole_vel = observations[:, 4]
    
    # Compute pole angle from cos and sin
    pole_angle = np.arctan2(sin_angle, cos_angle)
    
    # Plot position (cart position and pole angle)
    fig1 = plt.figure(figsize=(10, 6))
    plt.subplot(2, 1, 1)
    plt.plot(times, cart_pos, label="Cart Position", color="blue")
    plt.ylabel("Cart Position (m)")
    plt.xlabel("Time (s)")
    plt.legend()
    plt.grid(True)
    
    plt.subplot(2, 1, 2)
    plt.plot(times, pole_angle, label="Pole Angle", color="orange")
    plt.ylabel("Pole Angle (rad)")
    plt.xlabel("Time (s)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    
    # Plot velocity
    fig2 = plt.figure(figsize=(10, 6))
    plt.subplot(2, 1, 1)
    plt.plot(times, cart_vel, label="Cart Velocity", color="blue")
    plt.ylabel("Cart Velocity (m/s)")
    plt.xlabel("Time (s)")
    plt.legend()
    plt.grid(True)
    
    plt.subplot(2, 1, 2)
    plt.plot(times, pole_vel, label="Pole Angular Velocity", color="orange")
    plt.ylabel("Pole Angular Velocity (rad/s)")
    plt.xlabel("Time (s)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    
    # Plot control
    fig3 = plt.figure(figsize=(10, 4))
    plt.plot(times, actions[:, 0], color="blue")
    plt.ylabel("Control Action")
    plt.xlabel("Time (s)")
    plt.title("Control Signal")
    plt.grid(True)
    plt.tight_layout()
    
    # Plot rewards
    fig4 = plt.figure(figsize=(10, 4))
    plt.plot(times, rewards, color="green")
    plt.ylabel("Reward")
    plt.xlabel("Time (s)")
    plt.title(f"Rewards (Total: {np.sum(rewards):.2f})")
    plt.grid(True)
    plt.tight_layout()
    
    # Create animation if frames were collected
    if len(frames) > 0:
        print(f"\nCreating animation with {len(frames)} frames...")
        
        fig_anim = plt.figure(figsize=(8, 6))
        img = plt.imshow(frames[0])
        plt.axis('off')
        plt.title("Cartpole Swingup - Trained Policy")
        
        def animate(i):
            img.set_data(frames[i])
            return [img]
        
        FPS = 1.0 / dt
        anim = animation.FuncAnimation(
            fig_anim, animate, frames=len(frames),
            interval=1000/FPS, blit=True, repeat=True
        )
        print(f"Animation created at {FPS:.1f} FPS")
    
    plt.show()
    
    # Cleanup
    vis_env.close()
    vec_env.close()
    eval_env.close()
    
    print("\nTest complete!")